language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  # - "3.6"
before_install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  # Create and set conda environment
  - source "$HOME"/miniconda/bin/activate root
  - conda env create python=$TRAVIS_PYTHON_VERSION -n gwdev --file dev_linux_env.yml
  - source activate gwdev
  - unset CONDA_ENV_PATH # because the older conda in miniconda sets this, confusing some tests
  - export PATH=`echo "$PATH" | sed -e s@"$HOME"/miniconda/bin:@@g`

  # Install mfnwt and mt3d-usgs
  - pip install https://github.com/modflowpy/pymake/zipball/master

  # Install python package
  - python setup.py install -v
before_script:
  - cd CampaspeModel/tests
script:
  - python build_exes.py
  - pytest
