name: gwdev
channels:
- conda-forge
- defaults
dependencies:
- backports=1.0
- backports.functools_lru_cache=1.5
- backports_abc=0.5
- ca-certificates=2018.1.18
- certifi=2018.1.18
- cycler=0.10.0
- enum34=1.1.6
- freetype=2.8.1
- functools32=3.2.3.2
- icu=58.2
- jpeg=9b
- jsmin=2.2.1
- libpng=1.6.34
- matplotlib=2.1.2
- more-itertools=3.2.0
- openssl=1.0.2n
- pandas=0.20.3
- pip=9.0.1
- pyparsing=2.2.0
- pyqt=5.6.0
- python=2.7.14
- python-dateutil=2.6.1
- pytz=2018.3
- qt=5.6.2
- setuptools=38.5.1
- simplejson=3.11.1
- singledispatch=3.4.0.3
- sip=4.18
- six=1.11.0
- ssl_match_hostname=3.5.0.1
- tornado=4.5.3
- vc=9
- vs2008_runtime=9.0.30729.6161
- wheel=0.30.0
- wincertstore=0.2
- zlib=1.2.11
- icc_rt=2017.0.4
- intel-openmp=2018.0.0
- mkl=2018.0.1
- numpy=1.13.1
- scipy=0.19.1
- gdal=2.2.3
- pytest=3.5.1
- pip:
  - backports-abc==0.5
  - backports.functools-lru-cache==1.5
  - backports.ssl-match-hostname==3.5.0.1
  - flopy==3.2.6
  - pyemu==0.4
  # HydroModelBuilder install
  - git+https://github.com/daniel-partington/HydroModelBuilder.git@dev-working
