package:
    name: campaspemodel
    version: "0.2"

source:
    git_url: https://github.com/daniel-partington/CampaspeModel.git
    sha1: 6332960687118bab3a194fe62934928798639268

build:
    number: 0

extra:
    channels:
        - conda-forge

requirements:
  build:
    - gdal
    - geos
    - proj4
    - numpy
    - pandas
    - openpyxl
    - nose
  run:
    - gdal
    - geos
    - proj4
    - numpy
    - pandas
    - openpyxl
    - nose
    - matplotlib

about:
    license: Copyright
